apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-s3-log-reader
  namespace: tekton-space
  labels:
    app.kubernetes.io/name: tekton-s3-log-reader
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789123:role/eks-cluster-tekton-dashboard-fluent-bit-role
