apiVersion: v1
kind: Service
metadata:
  name: tekton-s3-log-reader
  namespace: tekton-space
  labels:
    app.kubernetes.io/name: tekton-s3-log-reader
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: exporter
      protocol: TCP
      name: exporter
  selector:
    app.kubernetes.io/name: tekton-s3-log-reader
