serviceAccount:
  create: true
  name: fluent-bit
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789123:role/eks-cluster-tekton-dashboard-fluent-bit-role

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 64Mi

tolerations:
  - key: node.k8s/tekton-role
    operator: Equal
    value: task
    effect: NoSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node.k8s/role
              operator: In
              values:
                - tekton-task

config:
  inputs: |
    [INPUT]
        Name              tail
        Alias             tekton-semantic
        Path              /var/log/containers/*tekton-space*
        Exclude_Path      /var/log/containers/*fluent-bit*
        Parser            docker
        Tag               kube.tekton.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Mem_Buf_Limit     100MB
        Refresh_Interval  60
        DB                /var/log/fluentbit_tail.db
        DB.locking        true

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.tekton.*
        Merge_Log           Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Buffer_Size         64K
        Kube_Tag_Prefix     kube.tekton.
        Regex_Parser        kubernetes-tag

  outputs: |
    [OUTPUT]
        Name  stdout
        Match kube.tekton.*

    [OUTPUT]
        Name            s3
        Alias           s3_tekton_logs
        Match           kube.tekton.*
        bucket          fluent-bit-tekton-dashboard-log-storage
        region          eu-central-1
        total_file_size 250M
        upload_timeout  1m
        s3_key_format   /$TAG[2]/$TAG[3]/$TAG[4]/%Y%m%d%H%M%S.log
        s3_key_format_tag_delimiters .

  customParsers: |
    [PARSER]
        Name kubernetes-tag
        Format regex
        Regex (?<namespace_name>.+)\.(?<pod_name>.+)\.(?<container_name>.+)
